# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('instagram_account', models.TextField(default='', primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default='')),
                ('access_token', models.TextField(default='')),
            ],
        ),
    ]
